version: "3.9"

services:

  db:
    image: postgres:15
    container_name: db_homolog
    environment:
      POSTGRES_DB: financeiro_homolog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: tomcat:9
    container_name: app_homolog
    ports:
      - "8081:8080"
    volumes:
      - ./app/financeiro.war:/usr/local/tomcat/webapps/financeiro.war
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=financeiro_homolog
      - DB_USER=user
      - DB_PASS=pass
    depends_on:
      - db
